Delimiter option
jsaari97/netlify-ts pull request #10
Opened 2022-10-10 15:29 UTC by gewfy

As discussed this adds the possibility to have a custom delimiter.

2022-10-11 05:53 UTC, gewfy commented
Nice catch, makes sense! Will dig deeper into that.

2022-10-11 19:07 UTC, gewfy commented
Updated according to your request

2022-10-11 19:33 UTC, gewfy commented on src/widget/transform.ts
> +  toDelimiter(capitalize ? toCapitalized(name) : name, delimiter);
@jsaari97 I've changed approach a bit here and made sure to replace any existing delimiters too. With this you really get uniform type names. E.g. `kitchenSink_typed_list_type_2_object` with default options and where `type_2_object` is an actual name, can now with...
```javascript 
{ label:true, capitalize: true, delimiter: "" }
```
...become `KitchenSinkTypedListType2Object`.

WDYS?

2022-10-11 20:24 UTC, jsaari97 requested changes
Great job! 🎉 

One small change I would make is to define the default delimiter as a constant, eg `DEFAULT_DELIMITER` in the `constants.ts` file :)

2022-10-11 20:27 UTC, gewfy commented
Ofc! Done :)

2022-10-11 20:42 UTC, jsaari97 commented
@gewfy looks like you accidentally forgot to add the constant to the CLI option's default value :)

2022-10-12 05:55 UTC, gewfy commented
Doh! Fixed :)

2022-10-12 07:02 UTC, jsaari97 approved these changes

2022-10-12 07:25 UTC, merged